djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path('', include('django.contrib.flatpages.urls')),
    path('contacts/', include('django.contrib.flatpages.urls')),
    path('about/', include('django.contrib.flatpages.urls')),


]

posts/urls.py
from django.urls import path
from .views import PostsList, PostDetail, PostCreateNews, PostUpdate, PostDelete, SearchList, PostCreateArtcl, CategoryPostsList, subscribe
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('', PostsList.as_view(), name='post_list'),
    path('<int:pk>', cache_page(60*10)(PostDetail.as_view()), name='post_detail'),
    path('news/create/', PostCreateNews.as_view(), name='news_post_create'),
    path('news/<int:pk>/edit/', PostUpdate.as_view(), name='news_post_update'),
    path('news/<int:pk>/delete/', PostDelete.as_view(), name='news_post_delete'),
    path('articles/create/', PostCreateArtcl.as_view(), name='artcl_post_create'),
    path('articles/<int:pk>/edit/', PostUpdate.as_view(), name='artcl_post_update'),
    path('articles/<int:pk>/delete/', PostDelete.as_view(), name='artcl_post_delete'),
    path('search/', SearchList.as_view(), name='search_list'),
    path('categories/<int:pk>', CategoryPostsList.as_view(), name='category_posts_list'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.FloatField(default=0)

    def update_rating(self):
        post_r = self.post_set.aggregate(post_rating=Sum('rating'))
        cr = post_r.get('post_rating') * 3
        comments_r = self.user_id.comment_set.aggregate(comment_rating=Sum('rating'))
        self.rating = cr + comments_r.get('comment_rating')
        self.save()

    def __str__(self):
        return f'{self.user_id}'


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    subscribers = models.ManyToManyField(User)
    related_name = 'categories'

    def __str__(self):
        return f'{self.name}'

    def get_subscribers(self):
        return ",\n".join([str(p) for p in self.subscribers.all()])


class Post(models.Model):
    NEWS = "NEWS"
    ARTICLE = "ARTCL"
    CATEGORIES = ((NEWS, "News articles"), (ARTICLE, "Articles"))

    author_id = models.ForeignKey(Author, on_delete=models.CASCADE)
    category_type = models.CharField(max_length=5, choices=CATEGORIES, default=NEWS)
    created_at = models.DateTimeField(auto_now_add=True)
    category_id = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.title.title()}: {self.text[:20]}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def preview(self):
        txt = f"{self.text[:123]}..."
        return txt

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class PostCategory(models.Model):
    to_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    to_category = models.ForeignKey(Category, on_delete=models.CASCADE)




class Comment(models.Model):
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

posts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post


class PostFormArtcl(forms.ModelForm):
    # text = forms.CharField(min_length=20)  # another way

    class Meta:
        model = Post
        fields = ('title', 'author_id', 'category_id', 'text')  # __all__

    def clean(self):
        cleaned_data = super().clean()
        description = cleaned_data.get("text")
        if description is not None and len(description) < 20:
            raise ValidationError({
                "text": "Text must be more than 20 symbols."
            })

        return cleaned_data


class PostFormNews(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'author_id', 'category_id', 'text')

    def clean(self):
        cleaned_data = super().clean()
        description = cleaned_data.get("text")
        if description is not None and len(description) < 20:
            raise ValidationError({
                "text": "Text must be more than 20 symbols."
            })

        return cleaned_data

posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Category
from .filters import PostFilter, SearchFilter
from .forms import PostFormArtcl, PostFormNews


class PostsList(ListView):
    model = Post
    ordering = '-created_at'
    template_name = 'posts.html'
    context_object_name = 'posts'
    paginate_by = 10

    # Переопределяем функцию получения списка товаров
    def get_queryset(self):
        # Получаем обычный запрос
        queryset = super().get_queryset()
        # Используем наш класс фильтрации.
        # self.request.GET содержит объект QueryDict, который мы рассматривали
        # в этом юните ранее.
        # Сохраняем нашу фильтрацию в объекте класса,
        # чтобы потом добавить в контекст и использовать в шаблоне.
        self.filterset = PostFilter(self.request.GET, queryset)
        # Возвращаем из функции отфильтрованный список товаров
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем в контекст объект фильтрации.
        context['filterset'] = self.filterset
        return context


class CategoryPostsList(ListView):
    model = Post
    template_name = 'category_list.html'
    context_object_name = "category_items_list"

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        qs = Post.objects.filter(category_id=self.category).order_by('-created_at')
        print(qs)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['not_subscriber'] = self.request.user not in self.category.subscribers.all()
        context['category'] = self.category
        return context


@login_required
def subscribe(request, pk):
    user = request.user
    print(user)
    cat = Category.objects.get(id=pk)
    print(cat)
    cat.subscribers.add(user)
    msg = "You've been subscribed to"
    return render(request, 'subscribe.html', {'category': cat, 'message': msg})


class SearchList(ListView):
    model = Post
    ordering = '-created_at'
    template_name = 'searchposts.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = SearchFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filtersearch'] = self.filterset
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'


class PostCreateArtcl(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = ('posts.add_post',)
    raise_exception = True
    form_class = PostFormArtcl
    model = Post
    template_name = 'post_edit.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.category_type = "ARTCL"
        return super().form_valid(form)


class PostCreateNews(PermissionRequiredMixin, CreateView):
    permission_required = ('posts.add_post',)
    form_class = PostFormNews
    model = Post
    template_name = 'post_edit.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.category_type = "NEWS"
        return super().form_valid(form)


class PostUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('posts.change_post',)
    form_class = PostFormArtcl
    model = Post
    template_name = 'post_edit.html'


class PostDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('posts.delete_post',)
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')

templates/category_list.html
{% extends 'flatpages/default.html' %}
{% load custom_tags %}

{% load custom_filters %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <h1>All posts</h1>

    <br>
    <a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Sign up for updates</a>

    {% if category_items_list %}
        <h3>Total posts: {{ category_items_list|length }}</h3>
        <table>
        <tr>
            <td>Title</td>
            <td>Date</td>
            <td>Description</td>
        </tr>

        {% for post in category_items_list %}
            <tr>
                <td>{{ post.title|censorship }}</td>
                <td>{{ post.created_at|date:'d M Y' }}</td>
                <td>{{ post.text|truncatechars:20|censorship }}</td>
                <td> Rating: {{ post.rating }} </td>
                <td> Category:
                    {% for category in post.category_id.all %}
                        <a href={% url 'category_posts_list' category.id %}> {{ category }}</a>
                    {% endfor %} </td>
            </tr>

            {#                <td>#}
            {#                     А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
            {#                    {% if perms.simpleapp.change_product %}#}
            {#                        <a href="{% url 'news_post_update' pk=product.id %}">Edit</a>#}
            {#                    {% endif %}#}
            {#                    {% if perms.simpleapp.delete_product %}#}
            {#                        <a href="{% url 'news_post_delete' product.id %}">Delete</a>#}
            {#                    {% endif %}#}
            {#                </td>#}
        {% endfor %}


    {% else %}
        <h2>No topics available</h2>

    {% endif %}

{% if page_obj.has_previous %}
    <a href="?{% url_replace page=1 %}">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{# current page info #}
{{ page_obj.number }}

{# next pages info #}
{% if page_obj.has_next %}
    <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page_obj.next_page_number %}
        ...
        <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}

{% endblock content %}

templates/new_post_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New post is waiting for you!</title>
</head>
<body>
<h1>Hello, there is a new <a href="{{ url }}">article in your favorite category</a></h1>
<p>{{ preview }}</p>
</body>
</html>

templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
    {% if post %}
        <ul>{{ post.title|censorship }}</ul>
        <ul>{{ post.created_at|date:'d M Y' }}</ul>
        <ul>{{ post.text|censorship }}</ul>
    {% endif %}
{% endblock content %}

templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Deletion</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Post</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/posts.html
{% extends 'flatpages/default.html' %}
{% load custom_tags %}

{% load custom_filters %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <h1>All posts</h1>

    {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
    <form action="" method="get">
        {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
        {{ filterset.form.as_p }}
        {# Добавим кнопку отправки данных формы #}
        <input type="submit" value="Search"/>
    </form>
{#        <br>#}
{#        <form action="/subscribe-news/" method="get">#}
{#            <input type="submit" value="Sign up for NEWS"/>#}
{#        </form>#}
{#                <form action="/subscribe-articles/" method="get">#}
{#            <input type="submit" value="Sign up for ARTICLES"/>#}
{#        </form>#}

    {% if posts %}
        <h3>Total posts: {{ posts|length }}</h3>
        <table>
            <tr>
                <td>Title</td>
                <td>Date</td>
                <td>Description</td>
            </tr>

            {% for post in posts %}
                <tr>
                    <td>{{ post.title|censorship }}</td>
                    <td>{{ post.created_at|date:'d M Y' }}</td>
                    <td>{{ post.text|truncatechars:20|censorship }}</td>
                    <td> Rating: {{ post.rating }} </td>
                    <td> Category:
                        {% for category in post.category_id.all %}
                            <a href={% url 'category_posts_list' category.id %}> {{ category }}</a>
                        {% endfor %} </td>
{#                    <td><a href="{% url'category_posts_list' category.id %}"?{{ post.get_category_type_display }}</> </td>#}
                </tr>

                {#                <td>#}
                {#                     А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                {#                    {% if perms.simpleapp.change_product %}#}
                {#                        <a href="{% url 'news_post_update' pk=product.id %}">Edit</a>#}
                {#                    {% endif %}#}
                {#                    {% if perms.simpleapp.delete_product %}#}
                {#                        <a href="{% url 'news_post_delete' product.id %}">Delete</a>#}
                {#                    {% endif %}#}
                {#                </td>#}
            {% endfor %}


    {% else %}
        <h2>No topics available</h2>

    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {# current page info #}
    {{ page_obj.number }}

    {# next pages info #}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

templates/searchposts.html
{% extends 'flatpages/default.html' %}
{% load custom_tags %}

{% load custom_filters %}

{% block title %}
    Search Posts
{% endblock title %}

{% block content %}
    <h1>Search posts</h1>


    <form action="" method="get">

        {{ filtersearch.form.as_p }}




{#        <label for="datetime">Date:</label>#}
{#        <input#}
{#                id="datetime"#}
{#                type="date"#}
{#                name="time_picker"#}
{#                value=""/>#}

 <input type="submit" value="Search"/>
    </form>

    {% if posts %}
        <h3>Total posts: {{ posts|length }}</h3>
        <table>
            <tr>
                <td>Title</td>
                <td>Date</td>
                <td>Description</td>
            </tr>

            {% for post in posts %}
                <tr>
                    <td>{{ post.title|censorship }}</td>
                    <td>{{ post.created_at|date:'d M Y' }}</td>
                    <td>{{ post.text|truncatechars:20|censorship }}</td>
                </tr>
            {% endfor %}

        </table>

    {% else %}
        <h2>No topics available</h2>

    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {# current page info #}
    {{ page_obj.number }}

    {# next pages info #}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

templates/subscribe.html
{% extends 'flatpages/default.html' %}
{% block content %}

    <h1 class="text-center">{{ message }} {{ category }}</h1>

{% endblock content %}

templates/weekly.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Hello again! Your weekly list is down here:</h1>

<ul>

    {% for post in posts %}
    <li><a href="{{ url }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}

</ul>

</body>
</html>